version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mylibrary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mylibrary

    ports:
      - "3306:3306"
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d


